# FROM alpine #, or your favorite tiny image
# ADD src/files /var/www/html/files
# VOLUME /var/www/html/files


# ADD docker/gitea-pg-data/ /var/lib/postgresql/data
# ADD docker/gitea-pg-logs /logs
# VOLUME /gitea-pg/

FROM postgres:15.2-bullseye
RUN mkdir /logs
RUN chown postgres:postgres /logs