#!/bin/bash

# this script location: .../gitea/util/cp-no-bin
# gitea file location: .../gitea/

# this copies to $HOME/service/gitea/gitea
# rsync -av --progress ../gitea $HOME/service/gitea --exclude bin

destination_dir=$HOME/service

# this copies to $destination_dir
run-here() {
    gitea_dir="../../gitea"
    if [[ $# -eq 0 ]]; then
        rsync -av --progress ${gitea_dir} ${destination_dir} --exclude bin --exclude .git
    elif [[ -d $1 ]]; then
        destination_dir=$1
        rsync -av --progress ${gitea_dir} ${destination_dir} --exclude bin --exclude .git
    fi 
}

# this is run if called from cp.py
run-from-project-root() {
    gitea_dir="../gitea"
    if [[ $# -eq 0 ]]; then
        rsync -av --progress ../gitea ${destination_dir} --exclude bin --exclude .git
    elif [[ -d $1 ]]; then
        destination_dir=$1
        rsync -av --progress ${gitea_dir} ${destination_dir} --exclude bin --exclude .git
    fi
}